"""
Script simple para verificar qué está pasando con las ventas
"""
print("\n" + "="*80)
print("🔍 INSTRUCCIONES PARA DIAGNOSTICAR EL PROBLEMA DE VENTAS")
print("="*80 + "\n")

print("PASO 1: Verifica que el webhook esté configurado")
print("-" * 80)
print("El webhook de Mercado Pago debe apuntar a:")
print("   https://prouniversity-exculpatory-latosha.ngrok-free.dev/api/checkout/webhook")
print()
print("Para verificar:")
print("   1. Ve a https://www.mercadopago.com.ar/developers")
print("   2. Entra a tu aplicación")
print("   3. Ve a 'Webhooks'")
print("   4. Verifica que la URL sea correcta")
print()

print("PASO 2: Realiza una compra de prueba")
print("-" * 80)
print("   1. Agrega un producto al carrito")
print("   2. Ve al checkout")
print("   3. Completa los datos de envío")
print("   4. Haz clic en 'REALIZAR PEDIDO'")
print("   5. Se abrirá una ventana emergente con Mercado Pago")
print("   6. Usa una tarjeta de prueba:")
print("      • Número: 4509 9535 6623 3704")
print("      • CVV: 123")
print("      • Vencimiento: 11/25")
print("   7. Completa el pago")
print()

print("PASO 3: Revisa los logs del backend")
print("-" * 80)
print("Después de completar el pago, busca en los logs del Docker:")
print()
print("Deberías ver estos mensajes:")
print("   🔔 Webhook recibido de Mercado Pago")
print("   💳 Procesando pago con ID: XXXX")
print("   📋 Información del pago obtenida de MP. Estado: approved")
print("   ✅ Pago aprobado, creando orden...")
print("   💾 Guardando orden en la base de datos...")
print("   🔄 Haciendo commit de la transacción...")
print("   ✅ Orden guardada exitosamente para el pago XXXX")
print()
print("Si NO ves estos mensajes:")
print("   ❌ El webhook NO se está ejecutando")
print("   ❌ Verifica la configuración en Mercado Pago")
print()

print("PASO 4: Si ves los mensajes, verifica el panel de admin")
print("-" * 80)
print("   1. Ve a http://localhost:5173/admin")
print("   2. Inicia sesión con tu usuario admin")
print("   3. Ve a la sección de 'Ventas'")
print("   4. Deberías ver la orden recién creada")
print()

print("PASO 5: Si NO aparece en el admin pero SÍ ves los logs")
print("-" * 80)
print("Entonces el problema está en el frontend o el endpoint GET")
print("   1. Abre la consola del navegador (F12)")
print("   2. Ve a la pestaña 'Network'")
print("   3. Busca la petición a '/api/admin/sales'")
print("   4. Verifica si hay errores")
print()

print("="*80)
print("\n💡 DATO IMPORTANTE:")
print("El webhook de Mercado Pago SOLO se ejecuta cuando:")
print("   - El pago fue aprobado")
print("   - Mercado Pago puede acceder a tu servidor (por eso usas ngrok)")
print("   - La URL del webhook está correctamente configurada")
print()
print("Si estás en desarrollo local, DEBES usar ngrok")
print("="*80 + "\n")
