version: '3.8'

services:
  backend:
    build:
      context: ./server
    container_name: void_backend_dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./client
    container_name: void_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      # Monta el código fuente para hot-reloading
      - ./client:/app
      # Evita que la carpeta node_modules local sobreescriba la del contenedor
      - /app/node_modules
    environment:
      # Habilita el polling para que Vite detecte cambios de archivos en Docker
      - CHOKIDAR_USEPOLLING=true
