services:
  backend:
    build:
      context: ./server
    container_name: void_backend_dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    # LA LÍNEA 'env_file' NO EXISTE MÁS. CHAU PROBLEMA.
    # El 'command' lo maneja el Dockerfile por defecto.
    depends_on:
      - redis

  frontend:
    build:
      context: ./client
    container_name: void_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  redis:
    image: "redis:7-alpine"
    container_name: void_redis_dev
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning