services:
  backend:
    build:
      context: ./server
    container_name: void_backend_dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    # Le decimos de dónde sacar la configuración
    env_file:
      - ./.env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - redis

  frontend:
    build:
      context: ./client
    container_name: void_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  redis:
    image: "redis:7-alpine"
    container_name: void_redis_dev
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  worker:
    build:
      context: ./server
    container_name: void_worker_dev
    # ¡LÍNEA CLAVE QUE FALTABA! El worker también necesita la configuración.
    env_file:
      - ./.env
    command: ["celery", "-A", "celery_worker.celery_app", "worker", "--loglevel=INFO"]
    volumes:
      - ./server:/app
    depends_on:
      - redis