version: '3.8'

services:
  backend:
    build: .
    container_name: void_backend_dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # Le decimos que busque el archivo .env en la misma carpeta
    env_file:
      - ./.env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]