// Lista de prefijos telefónicos internacionales más comunes
export const countryPrefixes = [
    { code: '+54', country: 'Argentina', flag: '🇦🇷', iso: 'AR' },
    { code: '+1', country: 'Estados Unidos / Canadá', flag: '🇺🇸', iso: 'US' },
    { code: '+52', country: 'México', flag: '🇲🇽', iso: 'MX' },
    { code: '+34', country: 'España', flag: '🇪🇸', iso: 'ES' },
    { code: '+44', country: 'Reino Unido', flag: '🇬🇧', iso: 'GB' },
    { code: '+33', country: 'Francia', flag: '🇫🇷', iso: 'FR' },
    { code: '+49', country: 'Alemania', flag: '🇩🇪', iso: 'DE' },
    { code: '+39', country: 'Italia', flag: '🇮🇹', iso: 'IT' },
    { code: '+351', country: 'Portugal', flag: '🇵🇹', iso: 'PT' },
    { code: '+55', country: 'Brasil', flag: '🇧🇷', iso: 'BR' },
    { code: '+56', country: 'Chile', flag: '🇨🇱', iso: 'CL' },
    { code: '+57', country: 'Colombia', flag: '🇨🇴', iso: 'CO' },
    { code: '+51', country: 'Perú', flag: '🇵🇪', iso: 'PE' },
    { code: '+598', country: 'Uruguay', flag: '🇺🇾', iso: 'UY' },
    { code: '+595', country: 'Paraguay', flag: '🇵🇾', iso: 'PY' },
    { code: '+593', country: 'Ecuador', flag: '🇪🇨', iso: 'EC' },
    { code: '+58', country: 'Venezuela', flag: '🇻🇪', iso: 'VE' },
    { code: '+506', country: 'Costa Rica', flag: '🇨🇷', iso: 'CR' },
    { code: '+507', country: 'Panamá', flag: '🇵🇦', iso: 'PA' },
    { code: '+86', country: 'China', flag: '🇨🇳', iso: 'CN' },
    { code: '+81', country: 'Japón', flag: '🇯🇵', iso: 'JP' },
    { code: '+82', country: 'Corea del Sur', flag: '🇰🇷', iso: 'KR' },
    { code: '+61', country: 'Australia', flag: '🇦🇺', iso: 'AU' },
];
