name: Backend CI - Docker Compose Tests

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Levantar servicios con Docker Compose
        # Ahora le decimos que el archivo de ejemplo está en la raíz.
        run: docker compose --env-file .env.example up --build -d backend redis

      - name: Esperar a que los servicios estén listos
        run: sleep 15

      - name: Correr Tests dentro del contenedor del Backend
        run: docker compose exec -T backend python -m pytest