name: Backend CI - Docker Compose Tests

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Preparar archivo .env para tests
        run: cp server/.env.example server/.env

      - name: Levantar servicios con Docker Compose
        # Levanta el backend y redis en segundo plano (-d) y reconstruye las imágenes (--build).
        run: docker compose up --build -d backend redis
      
      - name: Esperar a que los servicios estén listos
        run: sleep 15

      - name: Instalar dependencias de desarrollo en el contenedor
        run: docker compose exec -T backend pip install -r server/requirements-dev.txt

      - name: Correr Tests dentro del contenedor del Backend
        run: docker compose exec -T backend python -m pytest