name: Backend CI - Docker Compose Tests

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Preparar archivo .env para tests
        run: cp server/.env.example server/.env

      - name: Levantar servicios con Docker Compose
        # Este comando usa nuestro docker-compose.yml de la raíz.
        # Levanta el backend y redis en segundo plano (-d) y reconstruye las imágenes (--build).
        run: docker compose up --build -d backend redis
      
      - name: Esperar a que los servicios estén listos
        # Damos 10 segundos de changüí para asegurarnos de que Redis y la app
        # hayan tenido tiempo de inicializarse por completo.
        run: sleep 15

      - name: Correr Tests dentro del contenedor del Backend
        # ¡ACÁ ESTÁ LA MAGIA!
        # Usamos 'docker-compose exec' para ejecutar un comando DENTRO del
        # contenedor 'backend' que ya está corriendo.
        # El flag -T es para que no se queje de que no hay una terminal interactiva.
        run: >
          docker-compose exec -T backend
          python -m pytest