name: Backend CI - Docker Compose Tests

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Levantar servicios con Docker Compose
        # ==========================================================
        # ¡EL ÚNICO CAMBIO NECESARIO ESTÁ ACÁ!
        # Le pasamos el archivo de entorno AL COMANDO 'up'.
        # Esto asegura que el contenedor 'backend' arranque con la nafta puesta.
        # ==========================================================
        run: docker compose --env-file .env.example up --build -d

      - name: Esperar a que los servicios estén listos
        run: sleep 15

      - name: Correr Tests dentro del contenedor
        # Este comando ahora es más simple, porque el contenedor ya tiene
        # las variables de entorno cargadas desde el paso anterior.
        run: docker compose exec -T backend python -m pytest